apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0cd0b0a1a34f12d0d
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: static-ebs
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: static-pv
      mountPath: /usr/share/nginx/html
  volumes:
  - name: static-pv
    persistentVolumeClaim:
      claimName: ebs-static-claim
