apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-claim
spec:
  storageClassName: "expense-ebs" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: dynamic-ebs
  labels:
    project: expense
    storage: dynamic-pv
    environment: dev
spec:
# NodeSelector: topology.kubernetes.io/us-east-1f
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: dynamic-pv
      mountPath: /usr/share/nginx/html
  volumes:
  - name: dynamic-pv
    persistentVolumeClaim:
      claimName: ebs-dynamic-claim
---
apiVersion: v1
kind: Service
metadata:
  name: dynamic-ebs
spec:
  type: LoadBalancer
  selector: 
    project: expense
    storage: dynamic-pv
    environment: dev
  ports:
    - name: service-port
      protocol: TCP
      port: 80
      targetPort: 80
      