apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08e69fb82eb3c5ffe
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-efs-claim
spec:
  volumeName: expense-efs-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: expense-efs-pod
  labels:
    purpose: static-efs
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: expense-efs-pv
      mountPath: /usr/share/nginx/html
  volumes:
  - name: expense-efs-pv
    persistentVolumeClaim:
      claimName: expense-efs-claim
---
apiVersion: v1
kind: Service
metadata:
  name: static-ebs
spec:
  type: LoadBalancer
  selector: 
    purpose: static-efs
  ports:
    - name: service-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007