apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-claim
spec:
  storageClassName: "expense-efs-sc" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: dynamic-efs
  labels:
    purpose: efs-dynamic
spec:
# NodeSelector: topology.kubernetes.io/us-east-1f
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: dynamic-pv
      mountPath: /usr/share/nginx/html
  volumes:
  - name: dynamic-pv
    persistentVolumeClaim:
      claimName: efs-dynamic-claim
---
apiVersion: v1
kind: Service
metadata:
  name: dynamic-efs
spec:
  type: LoadBalancer
  selector: 
    purpose: efs-dynamic
  ports:
    - name: service-port
      protocol: TCP
      port: 80
      targetPort: 80
      