apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-efs-sc
reclaimPolicy: Retain
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-08e69fb82eb3c5ffe
  directoryPerms: "700"
  basePath: "/expense" # optional
  