apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: expense
  labels:
    Project: expense
    Env: dev
spec: 
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9
      command: ["sleep", "100"]


