apiVersion: v1
kind: Pod
metadata:
  name: environment
  labels:
  project: expense
spec:
 containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: "devops"
    - name: duration
      value: "120 hrs"
   