apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  annotations:
    buildurl: "https://hub.docker.com/"
  labels:
    project: expense
    module: backend
data:
  course: "devops"
  duration: "120 hrs"
spec:
  containers:
  - name: nginx
    image: nginx
   

