apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  annotations:
    buildurl: "https://hub.docker.com/"
  labels:
    project: expense
    module: backend
data:
  course: "devops"
  duration: "120 hrs"
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "68Mi"
      limits:
        cpu: "120m"
        memory: "100Mi"

