apiVersion: v1
kind: Pod
metadata:
  name: podconfig
  labels:
    project: expense
spec:
  containers:
    - name: nginx 
      image: nginx
      ports:
      - containerPort: 80
      env:
      - name: course
        valueFrom:
          configMapKeyRef:
          - name: configmap
            key: course
        valueFrom:
          configMapKeyRef:
          - name: configmap
            key: duration
