apiVersion: v1
kind: Pod
metadata:
  name: envfrom
  labels:
    project: expense
spec:
  containers:
    - name: nginx 
      image: nginx
      envFrom:
      - configMapRef:
          name: configmap
           
