apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster
spec:
  selector: 
    project: expense
    module: backend
    environment: dev
  ports:
    - name: service-port
    protocol: TCP
    port: 80
    targetPort: 80