apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector: 
    project: expense
    module: backend
    environment: dev
  ports:
    - name: service-port
      protocol: TCP
      port: 80
      targetPort: 80