apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    tier: frontend
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: nginx
  template:
    metadata:
       name: nginx-pod
       labels:
          tier: frontend
          app: nginx
    spec:
    containers:
    - name: nginx
      image: nginx
