apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    tier: frontend
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: nginx
  template:
    metadata:
       name: nginx-pod
       labels:
          tier: frontend
          app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-replicaservice
spec:
  selector: 
    tier: frontend
    app: nginx
  ports:
    - name: service-port
      protocol: TCP
      port: 80
      targetPort: 80
